// src/commands/show.ts
// `anatomy show [path] [--prose]` — display a parsed .anatomy file.
// --prose: render as natural language for AI context injection (stdout).
// Without --prose: emit the parsed document as JSON (stdout).

import { existsSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { parse } from "smol-toml";
import { readAnatomyFile } from "../io.js";
import { renderMemoryProse } from "../render/memory-prose.js";
import { pillarString } from "../render/identity.js";
import { parseMemoryDoc, readMemoryFile } from "../memory/io.js";

export interface ShowOptions {
  prose?: boolean;
  noMemory?: boolean;
  memoryOnly?: boolean;
  memoryLimitGotcha?: number;
  memoryLimitDecision?: number;
  memoryLimitAttempt?: number;
  memoryLimitMilestone?: number;
  memoryLimitConvention?: number;
}

function renderProse(doc: Record<string, unknown>): string {
  const lines: string[] = [];

  const id = doc.identity as Record<string, string> | undefined;
  const tagline = typeof doc.tagline === "string" ? doc.tagline : "";
  const description = typeof doc.description === "string" ? doc.description : "";

  if (tagline) lines.push(`# ${tagline}`);
  if (id) {
    // pillarString handles both v0.7 flat strings and v0.1-v0.6 nested {id,hash}.
    lines.push(`Stack: ${pillarString(id.stack)}  |  Form: ${pillarString(id.form)}  |  Domain: ${pillarString(id.domain)}  |  Function: ${pillarString(id.function)}`);
  }
  if (description) { lines.push(""); lines.push(description); }

  const op = doc.operation as Record<string, unknown> | undefined;
  if (op) {
    const cmds = op.commands as Record<string, string> | undefined;
    if (cmds && Object.keys(cmds).length > 0) {
      lines.push(""); lines.push("## Commands");
      for (const [k, v] of Object.entries(cmds)) lines.push(`  ${k}: ${v}`);
    }
    const eps = op.entry_points as Array<Record<string, string>> | undefined;
    if (eps && eps.length > 0) {
      lines.push(""); lines.push("## Entry points");
      for (const ep of eps) {
        const purpose = ep.purpose ?? ep.description ?? "";
        lines.push(`  ${ep.path} [${ep.role}]${purpose ? `: ${purpose}` : ""}`);
      }
    }
  }

  const sub = doc.substance as Record<string, unknown> | undefined;
  if (sub) {
    const deps = sub.key_dependencies as Array<Record<string, string>> | undefined;
    if (deps && deps.length > 0) {
      lines.push(""); lines.push("## Key dependencies");
      for (const d of deps) lines.push(`  ${d.name}: ${d.why}`);
    }
    // v0.8: substance.capabilities and substance.limitations were dropped — read older versions only.
    const caps = sub.capabilities as Array<Record<string, string>> | undefined;
    if (caps && caps.length > 0) {
      lines.push(""); lines.push("## Capabilities");
      for (const c of caps) lines.push(`  - ${c.phrase}`);
    }
    const lims = sub.limitations as Array<Record<string, string>> | undefined;
    if (lims && lims.length > 0) {
      lines.push(""); lines.push("## Limitations");
      for (const l of lims) lines.push(`  - ${l.phrase}`);
    }
  }

  const rules = doc.rules as Array<Record<string, string>> | undefined;
  if (rules && rules.length > 0) {
    lines.push(""); lines.push("## Rules");
    for (const r of rules) lines.push(`  - ${r.rule}${r.why ? ` (${r.why})` : ""}`);
  }

  const flows = doc.flows as Array<Record<string, string>> | undefined;
  if (flows && flows.length > 0) {
    lines.push(""); lines.push("## Data flows");
    for (const f of flows) lines.push(`  ${f.name}: ${f.summary}`);
  }

  const decisions = doc.decisions as Array<Record<string, string>> | undefined;
  if (decisions && decisions.length > 0) {
    lines.push(""); lines.push("## Decisions");
    for (const d of decisions) lines.push(`  ${d.topic}\n    ${d.reason}`);
  }

  const iface = doc.interface as Record<string, unknown> | undefined;
  if (iface) {
    const subs = iface.subcommands as Array<Record<string, string>> | undefined;
    if (subs && subs.length > 0) {
      lines.push(""); lines.push("## Subcommands");
      for (const s of subs) lines.push(`  ${s.name}: ${s.summary}`);
    }
    const exps = iface.exports as Array<Record<string, string>> | undefined;
    if (exps && exps.length > 0) {
      lines.push(""); lines.push("## Exports");
      for (const e of exps) lines.push(`  ${e.symbol} [${e.kind}]: ${e.summary}${e.signature ? ` — ${e.signature}` : ""}`);
    }
  }

  const gen = doc.generated as Record<string, unknown> | undefined;
  if (gen) {
    lines.push("");
    const commit = typeof gen.commit === "string" ? ` @ ${gen.commit}` : "";
    lines.push(`Generated by ${gen.by}${commit} using ${gen.model}`);
  }

  return lines.join("\n") + "\n";
}

export function showCommand(rawPath: string | undefined, opts: ShowOptions): number {
  const target = rawPath ?? "./.anatomy";
  if (!existsSync(target)) {
    process.stderr.write(`anatomy show: not found: ${target}\n`);
    return 1;
  }
  let filePath = target;
  if (statSync(target).isDirectory()) {
    filePath = join(target, ".anatomy");
    if (!existsSync(filePath)) {
      process.stderr.write(`anatomy show: no .anatomy in ${target}\n`);
      return 1;
    }
  }
  let text: string;
  try {
    text = readAnatomyFile(resolve(filePath));
  } catch (err) {
    process.stderr.write(`anatomy show: ${err instanceof Error ? err.message : String(err)}\n`);
    return 1;
  }
  try {
    const doc = parse(text) as Record<string, unknown>;
    if (!opts.prose) {
      process.stdout.write(JSON.stringify(doc, null, 2) + "\n");
      return 0;
    }

    // --prose path
    const repoRoot = dirname(resolve(filePath));
    let out = "";
    if (!opts.memoryOnly) {
      out = renderProse(doc);
    }
    if (!opts.noMemory) {
      const memText = readMemoryFile(repoRoot);
      if (memText) {
        try {
          const memDoc = parseMemoryDoc(memText);
          out += renderMemoryProse(memDoc, {
            limitGotcha: opts.memoryLimitGotcha,
            limitDecision: opts.memoryLimitDecision,
            limitAttempt: opts.memoryLimitAttempt,
            limitMilestone: opts.memoryLimitMilestone,
            limitConvention: opts.memoryLimitConvention,
          });
        } catch {
          // Silently skip memory section if parse fails — show command shouldn't error.
        }
      }
    }
    process.stdout.write(out);
    return 0;
  } catch (err) {
    process.stderr.write(`anatomy show: TOML parse error: ${err instanceof Error ? err.message : String(err)}\n`);
    return 1;
  }
}
