import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readExistingAgentsMd } from "../src/pass2/agents-md-input.js";

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "agents-md-input-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

describe("readExistingAgentsMd", () => {
  it("returns undefined when no AGENTS.md exists", () => {
    expect(readExistingAgentsMd(tmp)).toBeUndefined();
  });

  it("returns content when AGENTS.md exists", () => {
    writeFileSync(join(tmp, "AGENTS.md"), "# Hi\nsome rules");
    expect(readExistingAgentsMd(tmp)).toBe("# Hi\nsome rules");
  });

  it("truncates content over 3000 chars", () => {
    const long = "x".repeat(4000);
    writeFileSync(join(tmp, "AGENTS.md"), long);
    const out = readExistingAgentsMd(tmp)!;
    expect(out.length).toBeLessThan(4000);
    expect(out).toContain("[...truncated at 3000 chars");
  });

  it("returns undefined when AGENTS.md was generated by anatomy", () => {
    writeFileSync(
      join(tmp, "AGENTS.md"),
      "# X\n> **Regenerated from `.anatomy` at commit `abc` by `x`.**\n",
    );
    expect(readExistingAgentsMd(tmp)).toBeUndefined();
  });

  it("returns undefined when banner appears within first 10 lines (e.g., after MDC frontmatter)", () => {
    // The detection scans the first 10 lines. A banner at line 6 (after 4-line
    // YAML frontmatter + blank line) is correctly detected as generated.
    const content = "# Hi\n\nLine 3\nLine 4\nLine 5\n\nRegenerated from `.anatomy` at commit `x`";
    writeFileSync(join(tmp, "AGENTS.md"), content);
    expect(readExistingAgentsMd(tmp)).toBeUndefined();
  });

  it("returns content when banner-like text appears past first 10 lines", () => {
    // A hand-written file mentioning the banner string in prose past line 10
    // should not be considered generated.
    const content = "# Hi\n\nLine 3\nLine 4\nLine 5\n\nLine 7\nLine 8\nLine 9\nLine 10\nLine 11: Regenerated from `.anatomy` at commit `x`";
    writeFileSync(join(tmp, "AGENTS.md"), content);
    expect(readExistingAgentsMd(tmp)).toBe(content);
  });
});
