import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { listProviders, getProvider, selectProvider, ProviderError, type Pass2Provider } from "../src/pass2/providers/index.js";
import { enrichWithAI } from "../src/pass2/index.js";
import { runPass1 } from "../src/pass1/index.js";

const BIN = resolve(import.meta.dirname, "../dist/bin.js");

function runCli(
  args: string[],
  cwd: string,
): { stdout: string; stderr: string; code: number } {
  try {
    const stdout = execFileSync("node", [BIN, ...args], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    return { stdout, stderr: "", code: 0 };
  } catch (err) {
    const e = err as { stdout?: Buffer | string; stderr?: Buffer | string; status?: number };
    return {
      stdout: e.stdout?.toString() ?? "",
      stderr: e.stderr?.toString() ?? "",
      code: e.status ?? 1,
    };
  }
}

function makeRepo(): string {
  const root = mkdtempSync(join(tmpdir(), "anat-p2p-"));
  writeFileSync(join(root, "package.json"), JSON.stringify({
    name: "demo", version: "1.0.0", description: "Demo lib.",
    main: "./index.js", scripts: { test: "vitest" }, engines: { node: ">=20" },
  }));
  mkdirSync(join(root, "src"));
  return root;
}

// ── Provider registry ────────────────────────────────────────────────────────

describe("provider registry", () => {
  it("listProviders returns at least claude-cli", async () => {
    const all = await listProviders();
    const names = all.map(p => p.name);
    expect(names).toContain("claude-cli");
  });

  it("getProvider finds a registered provider by name", async () => {
    expect((await getProvider("claude-cli"))?.name).toBe("claude-cli");
  });

  it("getProvider returns undefined for unknown names", async () => {
    expect(await getProvider("definitely-not-a-real-provider")).toBeUndefined();
  });

  it("selectProvider with explicit name returns it", async () => {
    const p = await selectProvider("claude-cli");
    expect(p.name).toBe("claude-cli");
  });

  it("selectProvider throws ProviderError for unknown explicit name", async () => {
    await expect(selectProvider("nope")).rejects.toThrowError(ProviderError);
    await expect(selectProvider("nope")).rejects.toThrow(/unknown provider/);
  });
});

// ── ProviderError ────────────────────────────────────────────────────────────

describe("ProviderError", () => {
  it("carries the categorical code as a public field", () => {
    const e = new ProviderError("pass2-provider-network", "boom");
    expect(e.code).toBe("pass2-provider-network");
    expect(e.message).toBe("boom");
    expect(e.name).toBe("ProviderError");
    expect(e).toBeInstanceOf(Error);
  });
});

// ── enrichWithAI with --print-prompt ─────────────────────────────────────────

describe("enrichWithAI — printPromptOnly", () => {
  it("returns the prompt without calling any provider (modelId='dry-run')", async () => {
    const root = makeRepo();
    const pass1 = runPass1(root);
    const result = await enrichWithAI(pass1, root, { printPromptOnly: true });
    expect(result.modelId).toBe("dry-run");
    expect(result.prompt).toBeDefined();
    expect(result.prompt!.systemPrompt).toContain("filling in missing fields in a .anatomy");
    expect(result.prompt!.userPrompt).toContain("Fill in the TODO fields");
    // Pass1Result is unmodified.
    expect(result.result).toBe(pass1);
  });

  it("includes EXISTING_AGENTS_MD when a hand-written AGENTS.md is present", async () => {
    const root = makeRepo();
    writeFileSync(join(root, "AGENTS.md"), "# Hand-written\n- Rule: never use eval()\n");
    const pass1 = runPass1(root);
    const result = await enrichWithAI(pass1, root, { printPromptOnly: true });
    expect(result.prompt!.userPrompt).toContain("EXISTING_AGENTS_MD");
    expect(result.prompt!.userPrompt).toContain("Rule: never use eval()");
  });

  it("omits EXISTING_AGENTS_MD when AGENTS.md was generated by anatomy", async () => {
    const root = makeRepo();
    writeFileSync(
      join(root, "AGENTS.md"),
      "# x\n> **Regenerated from `.anatomy` at commit `abc` by `y`.**\nrest\n",
    );
    const pass1 = runPass1(root);
    const result = await enrichWithAI(pass1, root, { printPromptOnly: true });
    expect(result.prompt!.userPrompt).not.toContain("EXISTING_AGENTS_MD");
  });
});

// ── enrichWithAI with unknown provider ────────────────────────────────────────

describe("enrichWithAI — unknown provider", () => {
  it("propagates ProviderError when --provider names something unregistered", async () => {
    const root = makeRepo();
    const pass1 = runPass1(root);
    // pass1 must have at least one TODO for enrichWithAI to reach selectProvider.
    expect(pass1.identity.domain.isPlaceholder).toBe(true);
    await expect(
      enrichWithAI(pass1, root, { provider: "definitely-not-a-real-provider" }),
    ).rejects.toThrowError(ProviderError);
  });
});

// ── Custom provider injection (interface contract test) ──────────────────────

describe("Pass2Provider — custom mock provider", () => {
  it("enrichWithAI invokes provider.generate and parses its JSON response", async () => {
    // We can't register a third-party provider yet (Phase 3 work), but we can
    // verify enrichWithAI's contract by manually constructing the prompt the
    // provider would receive and asserting the orchestrator's plumbing.
    // (More complete coverage lives in ai-fill.test.ts which exercises
    // applyAiFill directly.)
    const root = makeRepo();
    const pass1 = runPass1(root);
    const printResult = await enrichWithAI(pass1, root, { printPromptOnly: true });
    expect(printResult.prompt!.systemPrompt.length).toBeGreaterThan(100);
    expect(printResult.prompt!.userPrompt.length).toBeGreaterThan(50);
  });

  it("provider can be looked up by name and asked for availability", async () => {
    const p = (await getProvider("claude-cli"))!;
    const avail = await p.available();
    // Don't assert true/false — depends on test environment. But the call
    // must complete without throwing and return a boolean.
    expect(typeof avail).toBe("boolean");
  });
});

// ── generate command flags ──────────────────────────────────────────────────

describe("anatomy generate — provider flags (CLI integration)", () => {
  it("--providers lists registered providers and exits 0", () => {
    const root = makeRepo();
    const r = runCli(["generate", "--providers"], root);
    expect(r.code).toBe(0);
    expect(r.stdout).toContain("Pass 2 providers:");
    expect(r.stdout).toContain("claude-cli");
    // Did not write a file.
    expect(existsSync(join(root, ".anatomy"))).toBe(false);
  });

  it("--print-prompt dumps system + user prompt and exits 0 without writing", () => {
    const root = makeRepo();
    const r = runCli(["generate", "--print-prompt"], root);
    expect(r.code).toBe(0);
    expect(r.stdout).toContain("system prompt");
    expect(r.stdout).toContain("user prompt");
    expect(r.stdout).toContain("Fill in the TODO fields");
    // No file written.
    expect(existsSync(join(root, ".anatomy"))).toBe(false);
  });

  it("--provider <unknown> exits 1 with ProviderError surfaced", () => {
    const root = makeRepo();
    const r = runCli(["generate", "--provider", "not-a-real-provider"], root);
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/unknown provider/);
  });

  it("--print-prompt does not check overwrite-protection (exit 0 even with existing .anatomy)", () => {
    const root = makeRepo();
    writeFileSync(join(root, ".anatomy"), "existing content");
    const r = runCli(["generate", "--print-prompt"], root);
    expect(r.code).toBe(0);
    expect(r.stdout).toContain("system prompt");
  });
});
