// src/render/write.ts
// Atomic batch writer for RenderArtifact arrays with banner-protected
// path handling.
//
// Two write paths:
//   1. .anatomy and any non-banner-protected path: atomic batch
//      (tmp + rename), preceded by mkdirSync for nested paths.
//   2. Banner-protected paths (AGENTS.md + v0.11 renderers): three-branch
//      strategy:
//        a) No existing file        -> write directly
//        b) Banner detected         -> overwrite (idempotent regen)
//        c) Hand-written (no banner)-> backup to .bak; prompt in TTY
//           mode; otherwise overwrite with stderr note.

import { writeFileSync, renameSync, existsSync, unlinkSync, readFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { createInterface } from "node:readline";
import type { RenderArtifact } from "./types.js";
import { hasRegenBanner } from "../banner.js";
import { unifiedDiff } from "../diff.js";

export interface WriteOptions {
  /** Auto-accept overwrite of hand-written banner-protected files without prompt.
   *  Defaults to true when stdin/stdout is not a TTY. */
  yes?: boolean;
}

/** Paths that get the banner-detection + backup write strategy. The substring
 *  test in hasRegenBanner is identical across all of these (they all contain
 *  the markdown banner line), so one detector serves all of them. */
const BANNER_PROTECTED_PATHS = new Set<string>([
  "AGENTS.md",
  ".cursor/rules/anatomy.mdc",
  ".cursorrules",
  "CONVENTIONS.md",
  ".clinerules",
  ".roorules",
  ".continuerules",
  ".windsurfrules",
]);

export async function writeArtifacts(
  repoRoot: string,
  artifacts: RenderArtifact[],
  opts: WriteOptions = {},
): Promise<void> {
  const protected_ = artifacts.filter((a) => BANNER_PROTECTED_PATHS.has(a.path));
  const others = artifacts.filter((a) => !BANNER_PROTECTED_PATHS.has(a.path));

  if (others.length > 0) {
    writeAtomicBatch(repoRoot, others);
  }
  for (const a of protected_) {
    await writeBannerProtected(repoRoot, a, opts);
  }
}

function ensureParentDir(absDst: string): void {
  const dir = dirname(absDst);
  mkdirSync(dir, { recursive: true });
}

function writeAtomicBatch(repoRoot: string, artifacts: RenderArtifact[]): void {
  const tmpPaths: string[] = [];
  try {
    for (const a of artifacts) {
      const dst = join(repoRoot, a.path);
      ensureParentDir(dst);
      const tmp = `${dst}.tmp`;
      writeFileSync(tmp, a.content, "utf8");
      tmpPaths.push(tmp);
    }
    for (const a of artifacts) {
      const dst = join(repoRoot, a.path);
      renameSync(`${dst}.tmp`, dst);
    }
  } catch (err) {
    for (const t of tmpPaths) {
      if (existsSync(t)) {
        try { unlinkSync(t); } catch { /* ignore cleanup errors */ }
      }
    }
    throw err;
  }
}

function writeArtifactAtomic(repoRoot: string, a: RenderArtifact): void {
  writeAtomicBatch(repoRoot, [a]);
}

async function writeBannerProtected(
  repoRoot: string,
  artifact: RenderArtifact,
  opts: WriteOptions,
): Promise<void> {
  const dst = join(repoRoot, artifact.path);

  // Branch 1: no existing file.
  if (!existsSync(dst)) {
    writeArtifactAtomic(repoRoot, artifact);
    return;
  }

  const existing = readFileSync(dst, "utf8");

  // Branch 2: existing has regen banner — idempotent overwrite.
  if (hasRegenBanner(existing)) {
    writeArtifactAtomic(repoRoot, artifact);
    return;
  }

  // Branch 3: hand-written file. Always write the backup first.
  const bakPath = `${dst}.bak`;
  writeFileSync(bakPath, existing, "utf8");

  const isTty = !!process.stdin.isTTY && !!process.stderr.isTTY;
  const yes = opts.yes ?? !isTty;

  if (isTty && !yes) {
    const diff = unifiedDiff(existing, artifact.content, artifact.path);
    process.stderr.write(
      `anatomy: ${artifact.path} exists and was not generated by anatomy.\n` +
      `Backup written to ${bakPath}.\n\n` +
      `Diff:\n${diff}\n\n` +
      `Overwrite ${artifact.path}? [y/N]: `,
    );
    const answer = (await readUserInput()).toLowerCase();
    if (answer !== "y" && answer !== "yes") {
      process.stderr.write(`Aborted. ${artifact.path} unchanged. Backup at ${bakPath}.\n`);
      return;
    }
  } else {
    process.stderr.write(
      `anatomy: overwriting hand-written ${artifact.path}; backup at ${bakPath}\n`,
    );
  }

  writeArtifactAtomic(repoRoot, artifact);
}

async function readUserInput(): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  return new Promise((resolve) => {
    rl.once("line", (line) => {
      rl.close();
      resolve(line.trim());
    });
  });
}
